### ISSUE TITLE
shape.fill_in_shape - docs unclear

### ISSUE THREAD

**Issue by michela** [acoullandreau/geo_rendering_package#3]
Using  Python 3.9.6
geo-rendering==1.1.0
numpy==1.21.4
opencv-python==4.5.4.60
pandas==1.3.4
pyshp==2.1.0
Shapely==1.8.0

Getting this error using fill_in_shape - is below the right syntax? Looking to fill in multiple shape files into one world map

```
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'fillPoly'
> Overload resolution failed:
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'
```

 project_shape_coords works fine  - to draw polyline

e.g.

```
    def render(self):
        logger.debug("render")
        shp_path = "./shp/World_Countries/World_Countries.shp"
        base_shapefile = geo_rendering.ShapeFile(shp_path)
        logger.debug(base_shapefile.df_sf)
        base_map = geo_rendering.Map(base_shapefile,[2048,1024])
        projection = geo_rendering.Projection(base_map)
        base_map.projection = projection
        for zone_id in base_map.shape_dict_filt:
            shape = base_map.shape_dict_filt[zone_id]
            #shape.project_shape_coords(base_map.projection)
            shape.fill_in_shape(base_map)
        base_map.render_map()
        filename = 'map_countries.png'
        cv2.imwrite(filename, base_map.map_file)
```

**Comment by acoullandreau** [comment]
Hello Michela!

I am glad someone else is trying to use this package!
As far as I understand, there is a problem with the type of data the
function fill_in_shape is using (behind the hood,  fill_in_shape calls the
function fillPoly from OpenCV).
You are passing base_map as a parameter to the function, that would be an
instance of the Map object, but it expects a numpy array. Could you try
passing base_map.map_file instead?

I hope this solves your problem!
By the way, I think this project could use some review to be simplified, if
you have some ideas let me know :D
Take care,

Alexina.
